services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sourcechat-postgres
    environment:
      POSTGRES_DB: sourcechat
      POSTGRES_USER: sourcechat
      POSTGRES_PASSWORD: sourcechat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sourcechat -d sourcechat"]
      interval: 10s
      timeout: 120s
      retries: 5
    networks:
      - sourcechat-network

  ollama:
    image: ollama/ollama:latest
    container_name: sourcechat-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - sourcechat-network
    entrypoint: ["bash","/entrypoint.sh"]

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  sourcechat-network:
    driver: bridge